import HoverCardDemo from '@/components/hoverCard'
import { RuiButton } from '@/components/shared/Button'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import RuiNavigationMenuDemo from '../components/navigationMenu'
import RuiTabs from '../components/tabs'
import RuiSlider from '../components/slider'
import RuiSeparator from '../components/separator'
import RuiSelect from '../components/select'
import RuiScrollArea from '../components/scrollArea'
import RuiRadioGroup from '../components/radioGroup'
import RuiProgress from '../components/progress'
import RuiPopover from '../components/popover'
import RuiMenuBar from '../components/menuBar'
import RuiLabel from '../components/label'
import RuiDropdownMenu from '../components/dropdownMenu'
import RuiContextMenu from '../components/contextMenu'
import RuiCollapsible from '../components/collapsible'
import RuiCheckbox from '../components/checkbox'
import RuiAvatar from '../components/avatar'
import RuiAspectRatio from '../components/aspectRatio'
import RuiAccordion from '../components/accordion'
import RuiToast from '../components/toast'
import RuiSwitch from '../components/switch'
import RuiToggle from '../components/toggle'
import RuiToggleGroup from '../components/toggleGroup'
import styles from '../styles/Home.module.css'


import { useTheme } from 'next-themes'
import RuiAlertDialog from '@/components/alertDialog'
import RuiDialog from '@/components/dialog'

const Home: NextPage = () => {

  const { setTheme, theme } = useTheme()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <RuiNavigationMenuDemo />
        <RuiAccordion />
        <RuiAvatar />
        <RuiAspectRatio />
        <RuiButton variant={'default'} size={'default'} onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>Eyebrain</RuiButton>
        <RuiCheckbox />
        <RuiCollapsible />
        <RuiContextMenu />
        <RuiDropdownMenu />
        <HoverCardDemo />
        <RuiLabel />
        <RuiMenuBar />
        <RuiPopover />
        <RuiProgress />
        <RuiRadioGroup />
        <RuiScrollArea />
        <RuiSelect />
        <RuiSeparator />
        <RuiSlider />
        <RuiSwitch />
        <RuiTabs />
        <RuiToast />
        <RuiToggle/>
        <RuiToggleGroup />
        <RuiAlertDialog />
        <RuiDialog/>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
